{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "weasley-clock.fullname" . }}-backend-data
  labels:
    {{- include "weasley-clock.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
